### ISSUE TITLE
Specify custom path for launcher

### ISSUE THREAD

**Issue by jbryson3** [testem/testem#1241]
My CI environment doesn't have Chrome or Chromium installed.  I would like to run my tests through one of those browsers. The easiest method would be to add something like [puppeteer](https://github.com/GoogleChrome/puppeteer) to my package.json, and then telling testem where to find the launcher's path in my node_modules directory.

Did I miss documentation that would allow me to do something like this?

**Comment by Techn1x** [comment]
I have a similar problem - I have installed puppeteer so that I can use headless chrome, and I have that path set in my environment (this would be a better method for you @jbryson3 ) so I can call this from anywhere
`chrome --version`

The trouble I am having is that puppeteer installs chrome as `chrome` rather than `google-chrome` which is what testem expects, see https://github.com/testem/testem/blob/master/lib/utils/known-browsers.js#L88-L90

If I add 'chrome' to that possibleExe array, it all works. But if I do this it will be clobbered every time I update node modules, so really I need one of the following;

* The ability to set a custom launcher name for the chrome browser in testem.js
OR
* Add 'chrome' to that possibleExe list (this is probably the easier option)

**Comment by jbryson3** [comment]
Well said @Techn1x - how have you handled the dynamic nature of download paths of puppeteer's Chromium?

puppeteer/.local-chromium/mac-{Version}/chrome-mac/Chromium.app/Contents/Chromium

**Comment by Techn1x** [comment]
To be honest, and I could be wrong (I don't think I did this myself unknowingly), when I installed puppeteer (as a package via npm) it added the correct location to my PATH variable
```
/home/ec2-user/.nvm/versions/node/v9.6.1/bin
/usr/local/rvm/gems/ruby-2.4.3/bin
/usr/local/rvm/gems/ruby-2.4.3@global/bin
/usr/local/rvm/rubies/ruby-2.4.3/bin
/usr/local/bin
/bin
/usr/bin
/home/ec2-user/.local/bin
/home/ec2-user/bin
/home/ec2-user/.nvm/versions/node/v9.6.1/lib/node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux
/usr/local/sbin
/usr/sbin
/sbin
/opt/aws/bin
/usr/local/rvm/bin
```

I haven't had puppeteer installed long enough for there to be a Chromium update, to know if it updates that PATH variable or not with the updated location

**Comment by jbryson3** [comment]
Good to know, thanks for the info @Techn1x 

I think my strategy is going to be to lock puppeteer at a certain revision https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables and then hardcode the path from there.

As my PR has been merged, I'm closing this ticket.
