### ISSUE TITLE
Allow specifying different combinations of bundled frameworks libraries(mocha, chai, jasmine, qunit, sinon, buster)

### ISSUE THREAD

**Issue by airportyh** [testem/testem#265]
Currently, the `framework` field in the config file has been piggybacked to allow direct out-of-the-box testing with mocha and chai using `framework: mocha+chai` - a common use case. But what about sinon? Maybe other spys and mock and assertion libraries? We can't jam everything into the `framework` field anymore. Need something more flexible. Perhaps

    frameworks:
        - mocha
        - chai
        - sinon

For the special case of chai which has multiple "interfaces" (bdd|tdd|qunit). It might be worth it configure the interface here using some sort of special syntax, perhaps steal the `!` from require.js.

    frameworks:
        - mocha
        - chai!tdd
        - sinon

**Comment by jasonkarns** [comment]
commenting here as an idea for the rewrite:

rather than bundling all the various frameworks and libraries (which results in version lag and attempting to handle all the various combinations) we improve the process by which libraries are added to the test page?

For example, I much prefer referencing mocha.js from `node_modules/` so if we improved the way scripts are added to the test page making it easier for node_modules scripts to be added, then we can keep all the test libraries/frameworks out of testem entirely.

Coupled with this, we'd need a way to inline script in the test page so as to configure the test framework (without needing an additional file whose contents may only be `mocha.ui('bdd')` )

**Comment by johanneswuerbach** [comment]
I definitely agree on that.

**Comment by johanneswuerbach** [comment]
Frameworks are no longer embedded and users are encouraged to use the custom runner https://github.com/testem/testem/pull/706 for more advanced use cases.
