### ISSUE TITLE
Various reports of disconnected browsers

### ISSUE THREAD

**Issue by johanneswuerbach** [testem/testem#777]
Developers seems to run into issues with testem 1+ about browsers randomly disconnecting.

https://github.com/ember-cli/ember-cli/issues/5414
http://discuss.emberjs.com/t/why-is-phantomjs-disconnecting/9636

@musaffa mind posting your OS and the browser(s) you tried, which had that issue?

**Comment by musaffa** [comment]
OS: Linux 3.13.0-27-generic Ubuntu x86_64
Phantomjs: 2.0.0

**Comment by jamesarosen** [comment]
The following *may* be germane, but I am not confident. Take with a grain of salt.

ember-cli/ember-cli#5414 -- each time I save a file, a new Chrome window opens to run the tests. If this happened only *once* (resulting in two windows), then it would suggest to me that the problem was in the browser half of the socket connection. Since *each* save opens a new window, I believe the fault may live in the (long-lived) server half. That is, after the first disconnect, the server is permanently unable to establish a connection with the browser.

We also see a separate scenario where after saving a file, the existing Chrome window reruns only those tests that passed in the last run instead of all tests. Clearly some part of the socket connection must still be working (or the browser wouldn't rerun anything automatically).

Is there something I could add to my app/test code that would help me diagnose the state of the connection? Maybe something to directly access Testem's in-browser socket.io connection? Check whether it's up, whether I can send messages to it. I haven't been able to find any Testem-related variables in my `window` to interact with.

**Comment by jamesarosen** [comment]
Another interesting finding: in the case where rebuilding (in Ember-CLI) opens new Chrome windows, the windows request and receive, but do not run `testem.js`.

<img width="563" alt="testem-response" src="https://cloud.githubusercontent.com/assets/2406/12773248/93b94884-c9ee-11e5-877c-886b3cd9391a.png">
<img width="591" alt="testem-headers" src="https://cloud.githubusercontent.com/assets/2406/12773249/93ea466e-c9ee-11e5-9d68-2739210aeeaa.png">

Here I've modified `testem/lib/server/index/js` as follows:
```js
async.forEachSeries(files, function(file, done) {
      if (file.indexOf(path.sep) === -1) {
        file = __dirname + '/../../public/testem/' + file;
      }
      fs.readFile(file, function(err, data) {
        if (err) {
          res.write('// Error reading ' + file + ': ' + err);
        } else {
          res.write('\n//============== ' + path.basename(file) + ' ==================\n\n');

          // added this line to show that testem is running:
          res.write('\nconsole.log("hello")\n\n');

          res.write(data);
        }
        done();
      });
    }, function() {
      res.write('}());');
      res.end();
    });
```
but nothing is printed to the console. Additionally, I can't place a debugger anywhere in that file.

I think the cause is this:

```
Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:7357/testem.js' with computed SHA-256 integrity 'FF22C27iNlNHmzP6SUryuSqR11CRDj+Ee+rcd95Ew0U='. The resource has been blocked.
```

**Comment by jamesarosen** [comment]
If I run testem locally (via ember-cli, with `ember test --serve --filter="..."`), then all the tests pass in the two environments I have specified (phantomjs and Chrome):

<img width="332" alt="testem-first-run" src="https://cloud.githubusercontent.com/assets/2406/12793922/7fc998e6-ca67-11e5-9794-5d083cc0e225.png">

 If I press Enter in the testem window to rerun the tests, I get the disconnected problem:

<img width="592" alt="testem-rerun-phantomjs" src="https://cloud.githubusercontent.com/assets/2406/12793928/891630d0-ca67-11e5-9427-4052fbae0c0d.png">
<img width="590" alt="testem-rerun-chrome" src="https://cloud.githubusercontent.com/assets/2406/12793932/8a42bd3e-ca67-11e5-95c9-a1997b33805d.png">

**Comment by jamesarosen** [comment]
The disconnect doesn't seem to interfere with the tests continuing to run or being reported back. It doesn't even interfere with `console.log` statements being shipped over the socket -- they appear in the Testem console as well.

Changing `onDisconnect` to the following lets our test suite pass just fine:
```js
onDisconnect: function() {
  var self = this;
  this.browser.pending = setTimeout(function() {
    if (self.finished) {
      return;
    }

    var result = {
      failed: 1,
      name: 'Browser ' + self.launcher.commandLine() + ' disconnected unexpectedly.'
    };
    // self.onTestResult.call(self, result); // don't report the failure and fail the build
    console.warn(result.name); // just log it
    self.finish();
  }, 1000);
},
```

**Comment by jmurphyau** [comment]
@johanneswuerbach I read the [ember forum post](http://discuss.emberjs.com/t/why-is-phantomjs-disconnecting/9636/7)

> I tried the same, but sadly phantomjs isn't logging anything so I skipped the logging for now. If somebody knows how to get more details from phantom before it crashes I'm happy to change that in testem. PhantomJS debugging is currently rough.

If you enable the remote debugger port in phantomjs you can then connect to it via a websocket and get console logs that appear to be more complete.. I've just been doing some work to figure out the messages to send and the format of the responses..

Before:

<img width="1179" alt="screen shot 2016-02-08 at 2 14 55 am" src="https://cloud.githubusercontent.com/assets/445432/12873145/3f8c388c-ce0a-11e5-81f1-7baaa7059093.png">

After:

<img width="1172" alt="screen shot 2016-02-08 at 2 11 53 am" src="https://cloud.githubusercontent.com/assets/445432/12873146/43bc52de-ce0a-11e5-87e8-78c070d716e0.png">

Keen to get something like this going in testem.. My experience with Ember development is that `SyntaxError: Parse error` causes me a lot of pain.. PhantomJS might timeout and not even show an error - then when checking the remote debugger and the issue is the old old version of WebKit that PhantomJS 1.9 uses can't parsing some of the JS..

I can open a PR for this if you like? Or maybe initially an issue for discussion (discuss the approach and where changes need to happen)

**Comment by johanneswuerbach** [comment]
Great findings! I would be open for a draft PR with a first draft and improve it in the future or an issue as you like.

**Comment by johanneswuerbach** [comment]
Testem `v1.2.2` should include a fix for this now. https://github.com/testem/testem/issues/781 Also the browser disconnect timeout is now configurable. Sorry for the long delay.

**Comment by musaffa** [comment]
Thanks it works now. Is this fix just a workaround?

**Comment by brancusi** [comment]
Works! Thank you!

**Comment by johanneswuerbach** [comment]
> Is this fix just a workaround?

@musaffa both a fix for the never reset pending timeout and a workaround for larg-ish apps sometimes need longer then a second to load before the testem client can report back to the testem server.

**Comment by musaffa** [comment]
:+1:

**Comment by jamesarosen** [comment]
#781 (v1.2.2) does not fix my disconnection issues. Using the default timeout of 10s, we now get

```
Built project successfully. Stored in "/home/travis/build/fastly/Tango/tmp/class-tests_dist-dDsqYlYt.tmp".
ok 1 PhantomJS 2.0 - JSCS - abilities: abilities/all.js should pass jscs
ok 2 PhantomJS 2.0 - JSHint - abilities: abilities/all.js should pass jshint
not ok 3 PhantomJS 2.0 - Browser "phantomjs /home/travis/build/fastly/Tango/node_modules/testem/assets/phantom.js http://localhost:7357/3782" exited unexpectedly with exit code null.
```

I'm trying some extra `console.log`ging now...

**Comment by fotinakis** [comment]
We can reliably reproduce this issue (both on CI and locally) by running a large test suite that ends up causing Chrome OOM issues. If Chrome's memory pressure manager decides to kill the tab (the standard `Aw Snap!` message if running normally), it will manifest as: `Browser "google-chrome ..." disconnected unexpectedly.`.

**Comment by joebartels** [comment]
I was able to mitigate the issue by playing with the `--memory-pressure-thresholds` flag

```js
// testem.js
  "browser_args": {
    "Chrome": [
      "--memory-pressure-thresholds 1"
    ]
  }
```
`4` makes it fail faster, and `1` is working out well for me so far...

Some resources that lead me to make the change:
https://bugs.chromium.org/p/chromium/issues/detail?id=449374
https://chromium.googlesource.com/chromium/src/+/f6f74b0eeeb0598b982f44f663405fb9ca919907/chrome/browser/about_flags.cc#290

**Comment by lolmaus** [comment]
`--memory-pressure-thresholds 1` didn't help me, still seeing this:

```
not ok 344 Chrome - error
    ---
        message: >
            Error: Browser disconnected
```

**Comment by ab9-er** [comment]
@lolmaus were you able to fix this? I am struggling with the same issue.

**Comment by fotinakis** [comment]
@ab9-er what environment or CI are you running Chrome in? Are you explicitly running it in docker at all? If so, I may have a fix for you.

**Comment by ab9-er** [comment]
@fotinakis Its on CI (Jenkins on Ubunutu 14.04) and yes it is running in a docker container.

**Comment by fotinakis** [comment]
@ab9-er (lots of debugging time spent on this problem) If you're running Chrome in Docker, and seeing disconnects (or "Aw Snap!" errors in headful xvfb windows), a very likely culprit is the size of shared memory via `/dev/shm` which Chrome uses extensively. When running inside a docker container, /dev/shm defaults to only 64MB (!), which can easily cause Chrome to crash after running for a while or when rendering a moderately complex page. See more details here: http://csmarosi.github.io/sigbus.html

If you're using docker-compose, you can add shm_size to your config:

```
services:
  app:
    image: my-chrome-image
    shm_size: 1G
```

**Comment by simonihmig** [comment]
@fotinakis thanks a lot! Luckily I found this issue and your solution before debugging this myself, certainly saved many many hours! 👍
