### ISSUE TITLE
XUnit output to stdout when xunit_intermediate_output and report_file are present?

### ISSUE THREAD

**Issue by rwjblue** [testem/testem#803]
When the `xunit_intermediate_output` option is set to true and `report_file` is specified, I believe we should disable printing the XUnit output to `process.stdout`.  When both options are set, we actually get test output in three places (the report file, the intermediate TAP style output in stdout, and a giant blob of xml in stdout). 

This is currently done [here](https://github.com/testem/testem/blob/40d3c2afe898ff566cedfa209bd3354b708a82e8/lib/report_file.js#L16), and should be a relatively simple fix/change.

@johanneswuerbach - I wanted to run this by you to see if you would generally be :+1: or :-1:...

**Comment by johanneswuerbach** [comment]
Yep, I think removing this makes totally sense :+1:

**Comment by rwjblue** [comment]
Awesome, I'll work on that after getting my other PR to pass...

**Comment by vvohra** [comment]
@johanneswuerbach Do you think this is still something do-able?

Since this issue was made the code has changed, so now a change is probably required somewhere [here](https://github.com/testem/testem/blob/master/lib/reporters/xunit_reporter.js#L39)

I'm wondering if I should try to make this generic, but I'm not sure if this is applicable to other reporters.
