### ISSUE TITLE
Tests hanging on Codeship

### ISSUE THREAD

**Issue by patocallaghan** [testem/testem#890]
I'm sorry for creating a vague issue but was just wondering if you have an feedback on this.

We're using Testem through Ember CLI but have found that none of our test runs pass in Codeship. That is, we split our tests and run them over multiple different pipelines in Codeship but that at least one of the test runs time out consistently. The tests run and get to the end but Codeship doesn't seem to know that they have completed and just hangs. The problem also is that there is no pattern to the timeouts. Different test runs fail each time so it's hard to reproduce manually. I can't reproduce locally unfortunately. 

This is what we are using:
Ember CLI 2.5.1
Testem 1.8.1
Node 5.10.1

I turned on Testem logging and managed to get the below logs:

```
info Test'em starting..
info Seeking for config file...
info Starting ci
info Starting server
info Start triggered test run.
info Running tests...
info spawning: google-chrome - [ '--user-data-dir=/tmp/testem-7308',
  '--no-default-browser-check',
  '--no-first-run',
  '--ignore-certificate-errors',
  '--test-type',
  '--disable-renderer-backgrounding',
  '--disable-background-timer-throttling',
  'http://localhost:7357/7308/tests/index.html?hidepassed=&filter=user-preview' ]
info New client connected: Chrome 51.0 7308
info tryAttach Chrome 51.0 7308
ERR! ENOENT: no such file or directory, stat 'path/to/tmp/class-tests_dist-BXrz75Ni.tmp/favicon.ico'
info Browser Chrome finished all tests. true
info Closing browser Chrome.
info Browser Chrome finished all tests. true
WARN Process Chrome not terminated in 5000ms.
info
```

I've been chatting with Codeship and they are adamant nothing has changed in their environment.
Do you know of any reasons why the Chrome instance wouldn't be terminated?

Funnily enough we also run our tests in another CI provider but we don't have the timeout issues there.

**Comment by patocallaghan** [comment]
Closing as not actionable

**Comment by YoranBrondsema** [comment]
@patocallaghan We're seeing similar issues, we're also on Codeship. Funny that you mention that it's only affecting Codeship. It's the only CI service that we use so we can't really compare but it could be a reason for us to change. What's the other provider that you are using?

We are basically seeing 3 scenarios, all happening at about equal ratio:

1. The test suite runs as you would expect it to run.
2. It's hanging, just like you describe. It's running for 30 minutes and the tests never seem to complete. Finally it exits with an error code.
3. It fails to start with the following error: `not ok 1 Browser "google-chrome --user-data-dir=/tmp/testem-3249 --no-default-browser-check --no-first-run --ignore-certificate-errors --test-type --disable-renderer-backgrounding --disable-background-timer-throttling http://localhost:7357/3249/tests/index.html?hidepassed" failed to connect. testem.js not loaded?`

Since your last comment, do you have any hints on why `testem` is failing so often on Codeship?

**Comment by patocallaghan** [comment]
@YoranBrondsema unfortunately we never found a solution. We worked with Codeship themselves to try and diagnose the issue but neither us nor them could work it out. Our other CI provider is CircleCi and our test suite runs just fine there.

**Comment by rupurt** [comment]
@patocallaghan we're seeing the same problem on CircleCI unfortunately :{
